### ISSUE TITLE
Disallow overlapping events

### ISSUE THREAD

**Issue by davisford** [bakineggs/recurring_events_for#1]
Hi, I realize this is a long shot as this is an old repo, and not probably being maintained anymore, but I've been reading and experimenting with [this solution](http://justatheory.com/computers/databases/postgresql/recurring_events.html) which led me here.

I have a slight twist in that I'd like to disallow overlapping event timestamps.  I was wondering if you had any quick pointers on how to enforce such a change?

**Comment by bakineggs** [comment]
One way you could disallow overlapping event timestamps is by using triggers. Create a trigger that fires on any inserts or updates and checks to make sure the new/changed row does not overlap with another event, raising an exception if it does.

**Comment by davisford** [comment]
Thanks, yea, I did go that route.
