### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by shorlbeck** [bakineggs/recurring_events_for#2]
Hi, I saw there was no license info, so I followed the link to the original source from which this was adapted, and noticed it is released under a [Creative Commons Attribution-NonCommercial 2.0 Generic](https://creativecommons.org/licenses/by-nc/2.0/) license. It's easy to assume that most stuff on GitHub is MIT but commercial developers may want to be aware of this license restriction.

**Comment by bakineggs** [comment]
I'll add a license file when I get back to a computer on Saturday (I only
have cell phone access to send an email reply right now and will be totally
off the grid between tomorrow and Saturday).
